### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by kenricci** [kdechant/angular5-httpclient-demo#2]
Installed 8.10.00 LTS of Nodejs on windows 10 and downloaded sample.
Ran npm install
Ran npm start and got the following:

C:\Users\ken.ricci\projects\angular5-httpclient-demo-master>npm start

> angular5-http-demo@1.0.0 start C:\Users\ken.ricci\projects\angular5-httpclient-demo-master
> ng build && node app.js

module.js:549
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ken.ricci\projects\angular5-httpclient-demo-master\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular5-http-demo@1.0.0 start: `ng build && node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular5-http-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ken.ricci\AppData\Roaming\npm-cache\_logs\2018-03-13T21_56_38_300Z-debug.log

**Comment by sanjit447** [comment]
This Error Was due to the Angular CLI version mismatch. Please update the the angular CLI version in Package.json and You are done Otherwise please follow the three step to solve it.

Step1: Edit your package.json changing the line
@angular/cli": "1.5.3"
to
@angular/cli": "^1.6.4"

Step2:
npm update -g @angular/cli 

Step3:
npm install --save-dev @angular/cli@latest

**Comment by kdechant** [comment]
I upgraded the app to Angular 5.2.9 and upgraded Angular CLI to v1.7.2. Please give it another try.
